avatar: /assets/img/hoho.png
title: "The DevOps Journey: From Zero to Engineer"
email: "elkim0118@gmail.com"
description: "This blog documents my journey from a non-technical background to becoming a DevOps Engineer. Follow along as I explore core concepts, hands-on projects, and problem-solving in Git, Docker, Kubernetes, AWS, CI/CD, and more. This is my professional learning log and a growing portfolio for my career in DevOps."
baseurl: ""
url: "https://elkim-ea.github.io" 
github_username: "elkim-ea"
linkedin_username: "www.linkedin.com/in/eunae-kim-6b2667313"


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
