# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"] # main 브랜치에 푸시될 때 워크플로우 실행
  workflow_dispatch: # Actions 탭에서 수동으로 실행 가능하게 함 (이게 'Run workflow' 버튼을 만듭니다!)

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated date is not used
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # 여기서 원하는 Ruby 버전 지정 (현재 3.2.2 사용 중이니 3.2로 명시)
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_url }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  # Deployment job
# Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        # id: deployment # id는 peaceiris 액션에서는 필요하지 않습니다. 이 줄은 삭제하거나 그대로 둡니다.
        uses: peaceiris/actions-gh-pages@v3 # PAT를 사용하는 액션으로 변경
        with:
          github_token: ${{ secrets.GH_PAT }} # 우리가 만든 Secret 이름
          publish_dir: ./_site # Jekyll 빌드 결과물이 있는 디렉토리
          # cname: 'yourdomain.com' # 사용자 정의 도메인을 사용한다면 주석 해제 후 여기에 도메인 입력 (지금은 필요 없음)
